version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"
    # Set a limit for pull requests
    open-pull-requests-limit: 10
    # Allow up to 5 dependencies to be updated in each pull request
    groups:
      dev-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Assign someone to review the PR
    assignees:
      - "jasgigli"
    # Configure version strategy
    versioning-strategy: auto

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      - "dependencies"
    assignees:
      - "jasgigli"
