blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/jasgigli/omni-request/discussions
    about: Please ask and answer questions here.
  - name: Security Issue
    url: https://github.com/jasgigli/omni-request/security/policy
    about: Please report security vulnerabilities here.
